endpoint_config = {
    "contacts": 1,
    "matters": 1,
    "leadsources": 1,
    "interactions": 1,
    "tasks": 1,
    "accounts": 1,
    "timeentries": 1,
    "expenses": 1,
    "flatfees": 1,
    "activities": 1,
    "reports/payment-collected": 1,
    "reports/invoice-history": 1,
    "reports/matter-balance": 1,
    "reports/client-trust": 1,
    "reports/client-ledger": 1,
    "reports/trust-ledger": 1,
    "reports/time-entries": 1,
    "reports/revenue": 1,
    "reports/accounts-receivable": 1,
    "reports/matters/info": 1,
    "users/me": 1,
    "users/teammates": 1,
    "users/team": 1,
    "users/data/contacts": 1,
    "users/data/matters": 1,
}

endpoint_logger_config = {
    "contacts": 1,
    "matters": 1,
    "leadsources": 1,
    "interactions": 1,
    "tasks": 1,
    "accounts": 1,
    "timeentries": 1,
    "expenses": 1,
    "flatfees": 1,
    "activities": 1,
    "reports": 1,
    "users": 1,
}
